name: Deploy to Vercel

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'backend/**' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Vercel CLI
      run: npm install -g vercel
      
    - name: Deploy to Vercel
      working-directory: ./backend
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
        else
          vercel --token ${{ secrets.VERCEL_TOKEN }} --yes
        fi
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} 